### ISSUE TITLE
couple of crashes

### ISSUE THREAD

**Issue by kx1t** [tedder/browser-screenshot-service#1]
Here are a couple of crashes I saw. 
The docker container was built with this command on `linux/arm64` (RPi4B Ubuntu 20.10):
`docker build -t screenshot:latest .`
This is the runtime command used to start the docker:
`docker run -p 5042:5042   -e MAP_ARGS='zoom=11&hideSidebar&hideButtons&mapDim=0' -e LOAD_SLEEP_TIME=3  -e BASE_URL='https://ramonk.net/tar1090/' -it screenshot:latest`
This was the request URL (from a remote machine on the same subnet):
`http://10.0.0.160:5042/snap/a55325`

Error messages:
```
pulling url: https://ramonk.net/tar1090/?icao=A55325&zoom=13&hideSidebar&hideButtons&mapDim=0
INFO:     10.0.0.153:49556 - "GET /snap/a55325 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/responder/api.py", line 361, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/trustedhost.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/responder/routes.py", line 342, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/responder/routes.py", line 136, in __call__
    await view(request, response, **path_params)
  File "/opt/app/snapapi.py", line 24, in snap_api
    img = get_screenshot(icao)
  File "/opt/app/snapapi.py", line 57, in get_screenshot
    raise Exception("no elements found (eg missing map canvas)")
Exception: no elements found (eg missing map canvas)
pulling url: https://ramonk.net/tar1090/?icao=A55325&zoom=13&hideSidebar&hideButtons&mapDim=0
INFO:     10.0.0.153:49780 - "GET /snap/a55325 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/responder/api.py", line 361, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/trustedhost.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/responder/routes.py", line 342, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/responder/routes.py", line 136, in __call__
    await view(request, response, **path_params)
  File "/opt/app/snapapi.py", line 24, in snap_api
    img = get_screenshot(icao)
  File "/opt/app/snapapi.py", line 54, in get_screenshot
    browser.get(url)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=88.0.4324.182)
```

**Comment by tedder** [comment]
I think I have the "tab crash" fixed by properly closing the browser (`with x as browser`). Added some experimentation with `shm` in there too.
